# Generated by Django 5.2.9 on 2025-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genus', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('Order', models.CharField(max_length=100)),
                ('HybProp', models.FloatField(blank=True, null=True)),
                ('Hyb_Ratio', models.FloatField(blank=True, null=True)),
                ('perc_per', models.FloatField(blank=True, null=True)),
                ('perc_wood', models.FloatField(blank=True, null=True)),
                ('perc_ag', models.FloatField(blank=True, null=True)),
                ('floral_symm', models.FloatField(blank=True, null=True)),
                ('mating_system', models.FloatField(blank=True, null=True)),
                ('repro_syndrome', models.FloatField(blank=True, null=True)),
                ('pollination_syndrome', models.FloatField(blank=True, null=True)),
                ('RedList', models.FloatField(blank=True, null=True)),
                ('tavg', models.FloatField(blank=True, null=True)),
                ('C_value', models.FloatField(blank=True, null=True)),
                ('Cv_C_value', models.FloatField(blank=True, null=True)),
                ('perc_per_text', models.CharField(blank=True, max_length=100, null=True)),
                ('perc_wood_text', models.CharField(blank=True, max_length=100, null=True)),
                ('perc_ag_text', models.CharField(blank=True, max_length=100, null=True)),
                ('floral_symm_text', models.CharField(blank=True, max_length=100, null=True)),
                ('mating_system_text', models.CharField(blank=True, max_length=100, null=True)),
                ('repro_syndrome_text', models.CharField(blank=True, max_length=100, null=True)),
                ('pollination_syndrome_text', models.CharField(blank=True, max_length=100, null=True)),
                ('redlist_text', models.CharField(blank=True, max_length=100, null=True)),
                ('tavg_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cvalue_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cv_cvalue_text', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
